---

- name: Install unzip
  apt:
    name: unzip
    update_cache: yes

- name: Create dependencies dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ dir_paths }}"

- name: Add 'portal-ext.properties' from template
  template:
    src: portal-ext.properties.j2
    dest: '{{ liferay_home }}/portal-ext.properties'
    mode: u=rw,g=r,o=r

- name: Add 'portal-setup-wizard.properties'
  copy:
    src: portal-setup-wizard.properties
    dest: "{{ liferay_home }}/"

- name: Download Postgresql driver
  get_url:
    url: '{{ dbdriver_url }}'
    dest: '{{ wildfly_dir }}/modules/com/liferay/portal/main/'

- name: Download dependencies
  unarchive:
    src: "{{ dependencies_link }}"
    dest: "{{ wildfly_dir }}/modules/com/liferay/portal/main"
    remote_src: yes

- name: Unpack dependencies
  command: mv {{ wildfly_dir }}/modules/com/liferay/portal/main/liferay-ce-portal-dependencies-{{ liferay_version }}/{{ item }} {{ wildfly_dir }}/modules/com/liferay/portal/main/{{ item }}
  with_items:
    - "{{ dependencies_lst }}"

- name: Copy 'module.xml' configuration
  copy:
    src: module.xml
    dest: "{{ wildfly_dir }}/modules/com/liferay/portal/main/"

- name: Download OSGI dependencies
  unarchive:
    src: "{{ osgi_link }}"
    dest: "{{ tmp_dir }}"
    remote_src: yes

- name: Move OSGI dependencies
  command: mv {{ tmp_dir }}/liferay-ce-portal-osgi-{{ liferay_version }}/{{ item }} {{ liferay_home }}/osgi/{{ item }}
  with_items:
    - configs
    - core
    - marketplace
