---

# kill
- name: Get running processes
  shell: "ps -ef | grep -v grep | grep -w java | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

# delete
- name: Delete directory
  file:
    path: '{{ base_dir }}'
    state: absent
