---

- name: Delete old if exists
  include: idempotency.yml

- name: Install java8 package
  apt:
    name: openjdk-8-jdk
    update_cache: yes

- name: Create Wildfly dir
  file:
    path: '{{ base_dir }}'
    state: directory
    mode: '0755'

- name: Download Wildfly
  unarchive:
    src: https://download.jboss.org/{{ wildfly_name }}/{{ wildfly_version }}/{{ wildfly_name }}-{{ wildfly_version }}.tar.gz
    dest: '{{ base_dir }}'
    remote_src: yes

- name: Replacing standalone.conf with a modified
  copy:
    src: standalone.conf
    dest: "{{ wildfly_dir }}/bin/standalone.conf"

- name: Create Wildfly user
  shell: '{{ wildfly_dir }}/bin/add-user.sh -u {{ wildfly_user }} -p {{ wildfly_password }}'

- name: Start Wildfly
  shell: 'nohup {{ wildfly_dir }}/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0 > /tmp/wildfly.log 2>&1 &'

- name: Download Postgresql driver
  get_url:
    url: '{{ dbdriver_url }}'
    dest: '{{ tmp_dir }}'

- name: Install Postgresql driver
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="module add --name=org.postgresql --resources={{ tmp_dir }}/{{ dbdriver_filename }} --dependencies=javax.api,javax.transaction.api"'

- name: Create Postgresql driver
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=datasources/jdbc-driver=postgres:add(driver-name="postgres",driver-module-name="org.postgresql",driver-class-name=org.postgresql.Driver)"'

- name: Add datasource to wildfly
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="data-source add --jndi-name=java:jboss/datasources/PostgresDS --name=PostgresDS --connection-url=jdbc:postgresql://{{ db_ip }}:5432/lportal --driver-name=postgres --user-name=lpuser --password=lppass"'

- name: Reload Wildfly
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect command=:reload'
