---
- name: Unarchive Prometheus
  unarchive:
    src: '{{ prometheus_repo }}'
    dest: '{{ base_dir }}'
    remote_src: yes
  register: unarchive_prometheus
  until: unarchive_prometheus is not failed
  retries: 5
  delay: 3

- name: Unarchive Postgres Exporter
  unarchive:
    src: '{{ postgres_exporter_repo }}'
    dest: '{{ base_dir }}'
    remote_src: yes
  register: unarchive_postgres_exporter
  until: unarchive_postgres_exporter is not failed
  retries: 5
  delay: 3

- name: Set environment for Postgres Exporter
  template:
    src: postgres_exporter.env
    dest: "{{ postgres_exporter_env_file }}"

- name: Create service in systemd for Postgres Exporter
  template:
    src: postgres_exporter.service
    dest: /etc/systemd/system/postgres_exporter.service

- name: Start Postgres Exporter on 9187 port
  systemd:
    name: postgres_exporter
    state: started
    enabled: yes
    daemon_reload: true

- name: Set new configuration for Prometheus with Postgres Exporter
  copy:
    src: prometheus.yml
    dest: "{{ prometheus_base_dir }}/prometheus.yml"

- name: Create service in systemd for Prometheus
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus on 9090 port
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: true
