---

# - name: Delete directory
#   file:
#     path: /etc/postgresql/
#     state: absent

- name: Apply key for postgresql repository
  shell:
    cmd: 'wget --quiet -O - {{ keys_url }} | sudo apt-key add -'
    warn: no
  # FIXME: TRY OUT THIS NEW STUFF
  # apt_key:
  #   url: {{ keys_url }}

- name: Add postgresql repository
  apt_repository:
    repo: 'deb {{ db_repo }} bionic-pgdg main'
    state: present
# FIXME: TRY OUT THIS NEW STUFF
# - apt_repository:
#     repo: deb http://archive.canonical.com/ubuntu hardy partner

- name: Install necessary linux packages
  apt:
    name: ["postgresql-9.6", "python3", "python3-pip"]
    update_cache: yes

- name: Install necessary python packages
  pip:
    name: psycopg2-binary

- name: Create LPortal database
  become: yes
  become_user: postgres
  postgresql_db:
    name: '{{ db_name }}'

- name: Create user lpuser
  become: yes
  become_user: postgres
  postgresql_user:
    db: '{{ db_name }}'
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: ALL
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,REPLICATION,BYPASSRLS

- name: Set access md5 to lpuser
  become: yes
  become_user: postgres
  postgresql_pg_hba:
    dest: '{{ db_hba_config }}'
    contype: local
    users: '{{ db_user }}'

- name: Set PostgreSQL to listen on default address
  shell: echo "listen_addresses = '*'" >> /etc/postgresql/9.6/main/postgresql.conf

- name: Set access to Postgresql by outside to lpuser
  become: yes
  become_user: postgres
  postgresql_pg_hba:
    dest: '{{ db_hba_config }}'
    contype: host
    users: '{{ db_user }}'
    source: 0.0.0.0/0

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
