#!groovy
properties([disableConcurrentBuilds()])

pipeline {
    agent { 
        label 'master'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {

        stage("run ansible-playbook postgresql") { 
            steps {
                ansiColor('xterm'){
                    ansiblePlaybook( 
                        playbook: '/user/share/tomcat/.jenkins/workspace/execute_ansible_roles/postgresql.yml',
                        inventory: '/user/share/tomcat/hosts.txt', 
                        credentialsId: '/user/share/tomcat/.ssh/id_rsa',
                        colorized: true)
                }         
            }
        }
        
        stage("run ansible-playbook wildfly") { 
            steps {
                ansiColor('xterm'){
                    ansiblePlaybook( 
                        playbook: '/user/share/tomcat/.jenkins/workspace/execute_ansible_roles/wildfly.yml',
                        inventory: '/user/share/tomcat/hosts.txt', 
                        credentialsId: '/user/share/tomcat/.ssh/id_rsa',
                        colorized: true)
                }         
            }
        }

        stage("run ansible-playbook liferay") { 
            steps {
                ansiColor('xterm'){
                    ansiblePlaybook( 
                        playbook: '/user/share/tomcat/.jenkins/workspace/execute_ansible_roles/liferay.yml',
                        inventory: '/user/share/tomcat/hosts.txt', 
                        credentialsId: '/user/share/tomcat/.ssh/id_rsa',
                        colorized: true)
                }         
            }
        }
        
        stage("run ansible-playbook monitoring") { 
            steps {
                ansiColor('xterm'){
                    ansiblePlaybook( 
                        playbook: '/user/share/tomcat/.jenkins/workspace/execute_ansible_roles/monitoring.yml',
                        inventory: '/user/share/tomcat/hosts.txt', 
                        credentialsId: '/user/share/tomcat/.ssh/id_rsa',
                        colorized: true)
                }         
            }
        }
    }
}