---

- name: Add <system-property>
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/system-property=org.apache.catalina.connector.URI_ENCODING:add(value=UTF-8)"'

- name: Add another one <system-property>
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/system-property=org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING:add(value=true)"'


- name: Add timeout for depployment scanner
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=deployment-scanner/scanner=default:write-attribute(name=deployment-timeout, value=600)"'


- name: Add PortalRealm
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=security/security-domain=PortalRealm/:add(cache-type=default)"'

- name: Config PortalRealm
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=security/security-domain=PortalRealm/authentication=classic:add(login-modules=[{"code"=>"com.liferay.portal.security.jaas.PortalLoginModule", "flag"=>"required"}])"'


- name: Config jsp
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=undertow/servlet-container=default/setting=jsp:write-attribute(name=development, value=true)"'

- name: Config jsp
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=undertow/servlet-container=default/setting=jsp:write-attribute(name=source-vm, value=1.8)"'

- name: Config jsp
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=undertow/servlet-container=default/setting=jsp:write-attribute(name=target-vm, value=1.8)"'


- name: Add filter-spec
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=logging/console-handler=CONSOLE:write-attribute(name=filter-spec, value=not(any(match(\"WFLYSRV0059|WFLYEE0007\"))))"'


- name: Remove microprofile subsystems metrics
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=microprofile-metrics-smallrye:remove()"'

- name: Remove microprofile extension metrics
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/extension=org.wildfly.extension.microprofile.metrics-smallrye:remove()"'

- name: Reload Wildfly
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect command=:reload'


- name: Remove microprofile subsystems config
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=microprofile-config-smallrye:remove()"'

- name: Remove microprofile extension config
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/extension=org.wildfly.extension.microprofile.config-smallrye:remove()"'

- name: Reload Wildfly
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect command=:reload'


- name: Remove microprofile subsystems health
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=microprofile-health-smallrye:remove()"'

- name: Remove microprofile extension health
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/extension=org.wildfly.extension.microprofile.health-smallrye:remove()"'

- name: Reload Wildfly
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect command=:reload'


- name: Remove microprofile subsystems opentracing
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=microprofile-opentracing-smallrye:remove()"'

- name: Remove microprofile extension opentracing
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/extension=org.wildfly.extension.microprofile.opentracing-smallrye:remove()"'

- name: Reload Wildfly
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect command=:reload'


- name: Remove tags weld from subsystem
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=weld:remove()"'

- name: Remove tags weld from extension
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/extension=org.jboss.as.weld:remove()"'


- name: Remove tags welcome-content location
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=undertow/server=default-server/host=default-host/location=\/:remove"'

- name: Remove tags welcome-content handler
  shell: '{{ wildfly_dir }}/bin/jboss-cli.sh --connect --command="/subsystem=undertow/configuration=handler/file=welcome-content:remove()"'
