---

- name: Get running processes
  shell: "ps -ef | grep -v grep | grep -w java | awk '{print $2}'"
  register: running_processes

- name: Kill running processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- name: Restart WildFly
  shell: 'nohup {{ wildfly_dir }}/bin/standalone.sh -b=0.0.0.0 -bmanagement=0.0.0.0 > /tmp/wildfly.log 2>&1 &'
