---
- name: Add an apt key from grafanas website
  apt_key:
    url: '{{ url_grafana_keys }}'

- apt_repository:
    repo: 'deb {{ url_grafana_repo }} stable main'

- name: Install necessary linux packages
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common
    - wget
    - grafana
    update_cache: yes

- name: Start Grafana on 3000 port
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: true

- name: Wait for connection
  wait_for_connection:

- name: Wait for port 3000 to become open on the host
  wait_for:
    port: '{{ port_grafana }}'
    delay: 5

- name: Set password to Grafana
  shell: 'grafana-cli --homepath {{ grafana_home }} admin reset-admin-password {{ grafana_admin_password }}'

- name: Add Prometheus Datasource
  grafana_datasource:
    grafana_url: 'http://{{ ip_grafana }}:{{ port_grafana }}'
    grafana_password: '{{ grafana_admin_password }}'
    ds_type: prometheus
    name: Prometheus
    url: http://localhost:9090

#- name: Download Postgres Dashboard json for Grafana
#  get_url:
#    url: https://grafana.com/api/dashboards/6742/revisions/1/download
#    dest: /etc/postgres_dashboard.json
#
#- name: Import Postgres Dashboard to Grafana
#  grafana_dashboard:
#    grafana_url: http://127.0.0.1:3000
#    grafana_password: 54321
#    path: /etc/postgres_dashboard.json # or 6742
